# for building

# version: "3.7"
# services:

#   dashboard_v2.4:
#     build: 
#       context: ./
#       dockerfile: ./docker/django/Dockerfile


# version: "3.7"

# services:

#   dashboard_v2:
#     image: &rpa2_dashboard rpa2_dashboard_v2.4
#     env_file: &envfile
#       - .env
#     command: bash -c "
#       python3 manage.py makemigrations 
#       && python3 manage.py migrate  
#       && python3 manage.py runserver 0.0.0.0:8001"
#     ports:
#       - 8080:8001
#     volumes: &vols
#       - ./bankasia/storage/resources/captcha:/rpa/bankasia/storage/resources/captcha
#       - ./bankasia/storage:/rpa/bankasia/storage
#       - ./db.sqlite3:/rpa/db.sqlite3
#       # - ./:/rpa
#     depends_on: 
#       - redis
#       - mqtt

#   redis:
#     image: redis

#   mqtt:
#     image: rpa2_mqtt
#     volumes:
#       - ./docker/mosquitto/:/mosquitto/
#     ports:
#       - 9001:9001
#       - 1883:1883
  
#   captcha-server:
#     image: nginx
#     volumes:
#       - ./bankasia/storage/resources/captcha:/usr/share/nginx/html:ro
#     ports:
#       - 3000:80

#   # bot 1 start ========================================
#   bot-1:
#     image: *rpa2_dashboard
#     env_file: *envfile
#     command: celery -A rpa2 worker -l info -Q bot_1
#     volumes:
#       - ./bankasia/storage/resources/captcha:/rpa/bankasia/storage/resources/captcha
#       - ./bankasia/storage_bot_1:/rpa/bankasia/storage
#       - ./db.sqlite3:/rpa/db.sqlite3
#       # - ./:/rpa
#     depends_on: 
#       - dashboard_v2
#       - node-nid-1
#       - node-abs-1
#       - captcha-server
#       - file-server-1

#   file-server-1:
#     image: nginx:test
#     volumes:
#       - ./bankasia/storage_bot_1:/root:ro
#     ports:
#       - 3001:80

#   node-abs-1:
#     image: hub.ferntechsolutions.com/selenium/standalone-chrome-debug:latest
#     volumes:
#       - /dev/shm:/dev/shm
#       - ./bankasia/storage_bot_1/temp_data:/home/seluser/Downloads
#     ports:
#       - 4444:4444
#       - 5901:5900
#   node-nid-1:
#     image: hub.ferntechsolutions.com/selenium/standalone-chrome-debug:latest
#     volumes:
#       - /dev/shm:/dev/shm
#     ports:
#       - 4445:4444
#       - 5902:5900
  
#   # bot 1 end ======================================

#   # bot 2 start =====================================
#   bot-2:
#     image: *rpa2_dashboard
#     env_file: *envfile
#     environment:
#       - NTH_ENTRY=10
#     command: celery -A rpa2 worker -l info -Q bot_2
#     volumes:
#       - ./bankasia/storage/resources/captcha:/rpa/bankasia/storage/resources/captcha
#       - ./bankasia/storage_bot_2:/rpa/bankasia/storage
#       - ./db.sqlite3:/rpa/db.sqlite3
#       # - ./:/rpa
#     depends_on: 
#       - dashboard_v2
#       - node-nid-2
#       - node-abs-2
#       - captcha-server
#       - file-server-2
  
#   file-server-2:
#     image: nginx:test
#     volumes:
#       - ./bankasia/storage_bot_2:/root:ro
#     ports:
#       - 3002:80

#   node-abs-2:
#     image: hub.ferntechsolutions.com/selenium/standalone-chrome-debug:latest
#     volumes:
#       - /dev/shm:/dev/shm
#       - ./bankasia/storage_bot_2/temp_data:/home/seluser/Downloads
#     ports:
#       - 4446:4444
#       - 5903:5900
#   node-nid-2:
#     image: hub.ferntechsolutions.com/selenium/standalone-chrome-debug:latest
#     volumes:
#       - /dev/shm:/dev/shm
#     ports:
#       - 4447:4444
#       - 5904:5900

  # bot 2 end =========================================


# for building
# version: "3"
# services:

#   bot:
#     build: 
#       context: ./
#       dockerfile: ./docker/Dockerfile

version: "3"

services:
  bot:
    image: sarvodayyumaya_bot
    command: 'sleep 20000'
    env_file: .env
    volumes: 
      - ./:/rpa
    depends_on:
      - node
    
  node:
    image: hub.ferntechsolutions.com/selenium/standalone-chrome-debug:latest
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4447:4444
      - 5901:5900
