# for building
# version: "3"
# services:

#   bot:
#     build: 
#       context: ./
#       dockerfile: ./docker/Dockerfile

version: "3"

services:
  bot:
    image: sarvodayyumaya_bot
    command: 'sleep 20000'
    env_file: .env
    volumes: 
      - ./client_data:/rpa/client_data
    depends_on:
      - node
    
  node:
    image: hub.ferntechsolutions.com/selenium/standalone-chrome-debug:latest
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4447:4444
      - 5901:5900
